# Experiments configuartion for long_term_forecast

# basic config
task_name: LTF
is_training: 1
model_id: Wspd6_wrf_calibrate
model: Informer

# data loader
data: turbine
root_path: ./datasets/WFP/
data_path: Turbine_Patv_Spd_15min_filled.csv
res_path: ./results/calibration/
features: S
target:
  - Wspd_6
subcol: []
freq: t
checkpoints: ./checkpoints/calibration/
test_idx: 1
run_seed: 2024

# hybrid training
use_hybrid:
  flag: false
  root_path: ./datasets/CFD/
  data_path: wrf_converted_turbine_data.csv
  target:
    - Wspd_6

# calibration setting
use_calibrate:
  flag: true
  root_path: ./datasets/WRF/
  data_path: extracted_wrf_data.csv
  target:
    - speed

# filter setting
use_filter:
  flag: false
  type: 0
  order: 5
  cutoff: 0.1

# forecasting task
seq_len: 96
label_len: 96
pred_len: 96
seasonal_patterns: Monthly
inverse: true

# inputation task
mask_rate: 0.25

# anomaly detection task
anomaly_ratio: 0.25

# model define
top_k: 5
num_kernels: 6
enc_in: 1
dec_in: 1
c_out: 1
d_model: 32
n_heads: 4
e_layers: 2
d_layers: 1
d_ff: 64
moving_avg: 25
factor: 1
distil: true
dropout: 0.15
embed: timeF
activation: gelu
output_attention: false
channel_independence: 0

# optimization
num_workers: 0
itr: 1
train_epochs: 10
batch_size: 32
patience: 3
learning_rate: 0.0001
des: test
loss: MSE
lradj: type1
use_amp: false
is_logging: true

# GPU
use_gpu: true
gpu: 0
use_multi_gpu: false
devices: 0,1,2,3

# de-stationary projector params
p_hidden_dims:
  - 128
  - 128
p_hidden_layers: 2
short_task_name: LTF